version: '3.8'
services:
  pg-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=helloworld
      - POSTGRES_PASSWORD=secretpassword
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  helloworld: &helloworld
    depends_on:
      - pg-db
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    restart: always
  helloworld-local:
    <<: *helloworld
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://pg-db:5432/helloworld"
volumes:
  db:
    driver: local