helloworld:
  jwt-secret: ${JWT_SECRET}
server:
  servlet:
    context-path: /helloworld
spring:
  application:
    name: helloworld
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:secretpassword}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/helloworld}
    username: ${SPRING_DATASOURCE_USERNAME:helloworld}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      datadog:
        api-key: ${DATADOG_API_KEY:data-dog-key}
        enabled: true
        step: 1m