helloworld:
  jwt-secret: jwt-secret
spring:
  datasource:
    username: helloworld
    password: secretpassword
    url: jdbc:postgresql://localhost:5432/helloworld
management:
  metrics:
    export:
      datadog:
        enabled: false