server:
  servlet:
    context-path: /helloworld
spring:
  application:
    name: helloworld
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect